# Generated by Django 5.2.5 on 2025-08-16 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('MRF', 'MRF'), ('CEAT', 'CEAT'), ('APOLLO', 'APOLLO'), ('JK', 'JK'), ('BRIDGESTONE', 'BRIDGESTONE')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('tube_type', models.CharField(choices=[('Tube', 'Tube'), ('Tubeless', 'Tubeless')], max_length=20)),
                ('quantity_shop1', models.PositiveIntegerField(default=0)),
                ('quantity_shop2', models.PositiveIntegerField(default=0)),
                ('invoice_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amazon_listed', models.BooleanField(default=False)),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('shop_name', models.CharField(max_length=50)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tyre')),
            ],
        ),
    ]
