# Generated by Django 5.2.5 on 2025-08-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salelog',
            name='tyre',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Tyre',
        ),
        migrations.DeleteModel(
            name='SaleLog',
        ),
    ]
