# Generated by Django 5.2.5 on 2025-08-16 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_salelog_tyre_remove_salelog_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('CEAT', 'CEAT'), ('APOLLO', 'APOLLO'), ('JK', 'JK')], max_length=50)),
                ('model_with_size', models.CharField(max_length=150)),
                ('tube_type', models.CharField(choices=[('Tube', 'Tube'), ('Tubeless', 'Tubeless')], max_length=20)),
                ('quantity_TS', models.PositiveIntegerField(default=0, verbose_name='Tirupur Stock')),
                ('quantity_GS', models.PositiveIntegerField(default=0, verbose_name='Gobi Stock')),
                ('invoice_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amazon_listed', models.BooleanField(default=False)),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(choices=[('TS', 'Tirupur Shop'), ('GS', 'Gobi Shop')], max_length=2)),
                ('customer_type', models.CharField(choices=[('Amazon', 'Amazon'), ('Retail', 'Retail')], max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.tyre')),
            ],
        ),
    ]
