# Generated by Django 5.0.6 on 2025-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='vehicle_type',
            field=models.CharField(choices=[('2W', '2 Wheeler'), ('PCR', 'Passenger Car Radial'), ('LCV', 'Light Commercial Vehicle'), ('SCV', 'Small Commercial Vehicle'), ('TBB', 'Truck Bias'), ('TBR', 'Truck Radial')], default='PCR', max_length=20),
        ),
    ]
